### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by FrostyLabs** [0x4D31/honeyku#2]
I get an error when I try and load it on heroku. Any pointers? (edit: I have not changed anything in ```config.json```)

Full error message: 

```
2019-01-08T20:37:06.280527+00:00 app[web.1]: [2019-01-08 20:37:06,275] ERROR in app: Exception on / [GET]

2019-01-08T20:37:06.280552+00:00 app[web.1]: Traceback (most recent call last):

2019-01-08T20:37:06.280555+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app

2019-01-08T20:37:06.280557+00:00 app[web.1]:     response = self.full_dispatch_request()

2019-01-08T20:37:06.280559+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request

2019-01-08T20:37:06.280561+00:00 app[web.1]:     rv = self.handle_user_exception(e)

2019-01-08T20:37:06.280563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception

2019-01-08T20:37:06.280565+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)

2019-01-08T20:37:06.280566+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise

2019-01-08T20:37:06.280568+00:00 app[web.1]:     raise value

2019-01-08T20:37:06.280570+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request

2019-01-08T20:37:06.280571+00:00 app[web.1]:     rv = self.dispatch_request()

2019-01-08T20:37:06.280573+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request

2019-01-08T20:37:06.280574+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)

2019-01-08T20:37:06.280576+00:00 app[web.1]:   File "/app/honeyku.py", line 51, in catch_all

2019-01-08T20:37:06.280579+00:00 app[web.1]:     if request.path in config['traps'] and request.path != "/favicon.ico":

2019-01-08T20:37:06.282093+00:00 app[web.1]: TypeError: 'NoneType' object is not subscriptable

2019-01-08T20:37:06.285941+00:00 app[web.1]: 10.45.34.88 - - [08/Jan/2019:20:37:06 +0000] "GET / HTTP/1.1" 500 291 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
```

**Comment by FrostyLabs** [comment]
Fixed, application was not loading the config file properly. Will close this issue now.
